import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext(null);

const dictionary = {
  en: {
    // Navigation
    'nav.browse': 'Browse Cars',
    'nav.bookings': 'My Bookings',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin Portal',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Log Out',
    // Hero Section
    'hero.tagline': 'Premium Fleet • Instant Confirmation',
    'hero.title': 'Drive Your Ambitions Anywhere',
    'hero.desc': 'Experience seamless car rentals with top agencies in your favorite cities. Choose from standard sedans, heavy SUVs, or high-performance sportscars.',
    // Search Panel
    'filter.city': 'Destination City',
    'filter.anywhere': 'Anywhere',
    'filter.pickup': 'Pickup Date',
    'filter.pickupTime': 'Pickup Time',
    'filter.return': 'Return Date',
    'filter.returnTime': 'Return Time',
    'filter.class': 'Car Class / Style',
    'filter.allClasses': 'All Classes',
    'filter.gearbox': 'Gearbox',
    'filter.anyGearbox': 'Any Transmission',
    'filter.automatic': 'Automatic',
    'filter.manual': 'Manual',
    'filter.budget': 'Daily Budget',
    'filter.reset': 'Reset Filters',
    'filter.search': 'Search Available Cars',
    // Landing Catalog
    'landing.fleet': 'Featured Fleet',
    'landing.sub': 'Choose from our handpicked premium selection',
    'landing.noCars': 'No Vehicles Found',
    'landing.noCarsSub': 'Try widening your search queries or resetting filters.',
    'landing.rent': 'Rent Now',
    'landing.day': 'day',
    // Car Details
    'carDetail.back': 'Back to Fleet',
    'carDetail.specs': 'Technical Specifications',
    'carDetail.brand': 'Brand',
    'carDetail.model': 'Model',
    'carDetail.year': 'Release Year',
    'carDetail.fuel': 'Fuel Type',
    'carDetail.class': 'Vehicle Class',
    'carDetail.description': 'Description',
    'carDetail.reviews': 'Verified Client Reviews',
    'carDetail.noReviews': 'No reviews have been left for this vehicle yet.',
    'carDetail.pricePerDay': 'Price per Day',
    'carDetail.bookNow': 'Instant Booking Request',
    'carDetail.freeCancel': 'Free cancellation up to 48 hours',
    'carDetail.rentedVia': 'Rented via',
    'carDetail.ownerCannotBook': 'Owners cannot book cars',
    'carDetail.logInToBook': 'Log In to Book',
    // Client Dashboard
    'client.title': 'My Bookings Dashboard',
    'client.sub': 'Track payments, manage active reservations, and write reviews',
    'client.noBookings': 'No Bookings Yet',
    'client.noBookingsSub': "You haven't reserved any vehicles. Ready to hit the road?",
    'client.payNow': 'Pay Now',
    'client.cancel': 'Cancel',
    'client.cancelRefund': 'Cancel & Refund',
    'client.writeReview': 'Write Review',
    'client.reviewed': 'Reviewed',
    'client.refundedAlert': 'Refund Processed',
    'client.refundedAmount': 'Refunded to Card',
    'client.cancelFee': 'Cancellation Fee',
    'client.leaveReviewTitle': 'Leave a Review',
    'client.leaveReviewSub': 'Share your experience renting this vehicle. Your feedback helps other drivers!',
    'client.ratingScore': 'Rating Score',
    'client.comment': 'Review Comment',
    // Owner Dashboard
    'owner.title': 'Agency Dashboard',
    'owner.sub': "Manage your agency's fleet, bookings, and financial logs",
    'owner.myFleet': 'My Fleet',
    'owner.bookingsLog': 'Bookings Log',
    'owner.earnings': 'Earnings Ledger',
    'owner.settings': 'Agency Settings',
    'owner.addCar': 'Add New Vehicle',
    'owner.emptyFleet': 'Your Fleet is Empty',
    'owner.emptyFleetSub': 'Register a vehicle to start receiving rental requests.',
    'owner.images': 'Images',
    'owner.agencyReg': 'Agency Registration',
    'owner.agencyRegSub': 'You must register your agency details before adding vehicles to the system.',
    'owner.brandName': 'Agency Brand Name',
    'owner.cityBase': 'City Base',
    'owner.officeAddress': 'Business Office Address',
    'owner.businessPhone': 'Business Phone Line',
    'owner.descPlaceholder': 'Describe your services or fleet specs...',
    'owner.submitApproval': 'Submit for Admin Approval',
    'owner.pendingApprovalTitle': 'Approval in Progress',
    'owner.pendingApprovalDesc': 'Your agency application is currently pending review by the platform administrator.',
    'owner.checkBack': 'Please check back shortly. You will be able to manage your fleet once approved.',
    'owner.editProfile': 'Update Agency Profile',
    'owner.submitUpdates': 'Submit Updates',
    // Admin Dashboard
    'admin.title': 'System Control Panel',
    'admin.sub': 'Global Platform Metrics, Security and Escrow Moderation',
    'admin.overview': 'Overview',
    'admin.agencies': 'Agencies',
    'admin.usersRegistry': 'User Registry',
    'admin.escrow': 'Escrow & Payments',
    'admin.reviewsMod': 'Reviews Moderation',
    'admin.totalClients': 'Total Clients',
    'admin.totalAgencies': 'Total Agencies',
    'admin.totalRevenue': 'Commission Profit',
    'admin.pendingEscrows': 'Pending Escrows',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.suspend': 'Suspend',
    'admin.activate': 'Activate',
    'admin.delete': 'Delete',
    'admin.releaseFunds': 'Release Funds',
  },
  fr: {
    // Navigation
    'nav.browse': 'Parcourir les voitures',
    'nav.bookings': 'Mes Réservations',
    'nav.dashboard': 'Tableau de bord',
    'nav.admin': 'Portail Admin',
    'nav.login': 'Connexion',
    'nav.register': 'S\'inscrire',
    'nav.logout': 'Déconnexion',
    // Hero Section
    'hero.tagline': 'Flotte Premium • Confirmation Instantanée',
    'hero.title': 'Conduisez vos ambitions partout',
    'hero.desc': 'Louez des véhicules en toute simplicité auprès des meilleures agences. Choisissez entre des berlines standards, des SUV robustes ou des sportives performantes.',
    // Search Panel
    'filter.city': 'Ville de destination',
    'filter.anywhere': 'Partout',
    'filter.pickup': 'Date de départ',
    'filter.pickupTime': 'Heure de départ',
    'filter.return': 'Date de retour',
    'filter.returnTime': 'Heure de retour',
    'filter.class': 'Catégorie de voiture',
    'filter.allClasses': 'Toutes les catégories',
    'filter.gearbox': 'Boîte de vitesses',
    'filter.anyGearbox': 'Toute transmission',
    'filter.automatic': 'Automatique',
    'filter.manual': 'Manuelle',
    'filter.budget': 'Budget journalier',
    'filter.reset': 'Réinitialiser les filtres',
    'filter.search': 'Rechercher les voitures',
    // Landing Catalog
    'landing.fleet': 'Notre Flotte',
    'landing.sub': 'Choisissez parmi notre sélection premium triée sur le volet',
    'landing.noCars': 'Aucun véhicule trouvé',
    'landing.noCarsSub': 'Essayez d\'élargir vos critères de recherche ou réinitialisez les filtres.',
    'landing.rent': 'Louer',
    'landing.day': 'jour',
    // Car Details
    'carDetail.back': 'Retour à la flotte',
    'carDetail.specs': 'Spécifications techniques',
    'carDetail.brand': 'Marque',
    'carDetail.model': 'Modèle',
    'carDetail.year': 'Année de sortie',
    'carDetail.fuel': 'Carburant',
    'carDetail.class': 'Catégorie de véhicule',
    'carDetail.description': 'Description',
    'carDetail.reviews': 'Avis clients vérifiés',
    'carDetail.noReviews': 'Aucun avis n\'a été laissé pour ce véhicule pour le moment.',
    'carDetail.pricePerDay': 'Prix par jour',
    'carDetail.bookNow': 'Réserver instantanément',
    'carDetail.freeCancel': 'Annulation gratuite jusqu\'à 48 heures',
    'carDetail.rentedVia': 'Loué via',
    'carDetail.ownerCannotBook': 'Les propriétaires ne peuvent pas louer de voitures',
    'carDetail.logInToBook': 'Se connecter pour réserver',
    // Client Dashboard
    'client.title': 'Mon Tableau de Bord',
    'client.sub': 'Suivez vos paiements, gérez vos réservations et laissez des avis',
    'client.noBookings': 'Aucune réservation',
    'client.noBookingsSub': 'Vous n\'avez loué aucun véhicule. Prêt à prendre la route ?',
    'client.payNow': 'Payer',
    'client.cancel': 'Annuler',
    'client.cancelRefund': 'Annuler & Rembourser',
    'client.writeReview': 'Laisser un avis',
    'client.reviewed': 'Évalué',
    'client.refundedAlert': 'Remboursement traité',
    'client.refundedAmount': 'Remboursé sur carte',
    'client.cancelFee': 'Frais d\'annulation',
    'client.leaveReviewTitle': 'Laisser un avis',
    'client.leaveReviewSub': 'Partagez votre expérience de location. Votre avis aide les autres conducteurs !',
    'client.ratingScore': 'Note d\'évaluation',
    'client.comment': 'Votre avis',
    // Owner Dashboard
    'owner.title': 'Tableau de bord de l\'agence',
    'owner.sub': 'Gérez votre flotte, vos réservations et vos rapports financiers',
    'owner.myFleet': 'Ma Flotte',
    'owner.bookingsLog': 'Réservations',
    'owner.earnings': 'Revenus',
    'owner.settings': 'Paramètres de l\'agence',
    'owner.addCar': 'Ajouter un véhicule',
    'owner.emptyFleet': 'Votre flotte est vide',
    'owner.emptyFleetSub': 'Enregistrez un véhicule pour commencer à recevoir des demandes.',
    'owner.images': 'Images',
    'owner.agencyReg': 'Enregistrement de l\'agence',
    'owner.agencyRegSub': 'Vous devez enregistrer votre agence avant d\'ajouter des véhicules.',
    'owner.brandName': 'Nom commercial',
    'owner.cityBase': 'Ville d\'attache',
    'owner.officeAddress': 'Adresse du bureau',
    'owner.businessPhone': 'Téléphone de l\'agence',
    'owner.descPlaceholder': 'Décrivez vos services ou spécificités...',
    'owner.submitApproval': 'Soumettre pour approbation',
    'owner.pendingApprovalTitle': 'Approbation en cours',
    'owner.pendingApprovalDesc': 'Votre demande d\'agence est en cours de révision par l\'administrateur.',
    'owner.checkBack': 'Veuillez revenir plus tard. Vous pourrez gérer votre flotte dès approbation.',
    'owner.editProfile': 'Mettre à jour l\'agence',
    'owner.submitUpdates': 'Enregistrer',
    // Admin Dashboard
    'admin.title': 'Panneau de contrôle système',
    'admin.sub': 'Statistiques de la plateforme, modération financière et sécurité',
    'admin.overview': 'Vue d\'ensemble',
    'admin.agencies': 'Agences',
    'admin.usersRegistry': 'Utilisateurs',
    'admin.escrow': 'Garanties & Paiements',
    'admin.reviewsMod': 'Modération des avis',
    'admin.totalClients': 'Total Clients',
    'admin.totalAgencies': 'Total Agences',
    'admin.totalRevenue': 'Bénéfice commissions',
    'admin.pendingEscrows': 'Paiements en attente',
    'admin.approve': 'Approuver',
    'admin.reject': 'Rejeter',
    'admin.suspend': 'Suspendre',
    'admin.activate': 'Activer',
    'admin.delete': 'Supprimer',
    'admin.releaseFunds': 'Libérer les fonds',
  },
  ar: {
    // Navigation
    'nav.browse': 'تصفح السيارات',
    'nav.bookings': 'حجوزاتي',
    'nav.dashboard': 'لوحة التحكم',
    'nav.admin': 'بوابة المسؤول',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'إنشاء حساب',
    'nav.logout': 'تسجيل الخروج',
    // Hero Section
    'hero.tagline': 'أسطول متميز • تأكيد فوري للحجوزات',
    'hero.title': 'قد طموحاتك إلى أي مكان',
    'hero.desc': 'استمتع بتجربة تأجير سيارات سلسة مع أفضل الوكالات في مدنك المفضلة. اختر من بين سيارات السيدان، الدفع الرباعي، أو السيارات الرياضية الفاخرة.',
    // Search Panel
    'filter.city': 'مدينة الوجهة',
    'filter.anywhere': 'كل المدن',
    'filter.pickup': 'تاريخ الاستلام',
    'filter.pickupTime': 'وقت الاستلام',
    'filter.return': 'تاريخ الإرجاع',
    'filter.returnTime': 'وقت الإرجاع',
    'filter.class': 'فئة السيارة',
    'filter.allClasses': 'كل الفئات',
    'filter.gearbox': 'ناقل الحركة',
    'filter.anyGearbox': 'أي ناقل حركة',
    'filter.automatic': 'أوتوماتيك',
    'filter.manual': 'يدوي',
    'filter.budget': 'الميزانية اليومية',
    'filter.reset': 'إعادة تعيين الفلاتر',
    'filter.search': 'بحث عن سيارات متاحة',
    // Landing Catalog
    'landing.fleet': 'أسطولنا المتميز',
    'landing.sub': 'اختر من بين تشكيلتنا الفاخرة المختارة بعناية',
    'landing.noCars': 'لم يتم العثور على سيارات',
    'landing.noCarsSub': 'حاول توسيع نطاق البحث أو إعادة تعيين الفلاتر.',
    'landing.rent': 'احجز الآن',
    'landing.day': 'يوم',
    // Car Details
    'carDetail.back': 'العودة للأسطول',
    'carDetail.specs': 'المواصفات التقنية',
    'carDetail.brand': 'الشركة المصنعة',
    'carDetail.model': 'الموديل',
    'carDetail.year': 'سنة الصنع',
    'carDetail.fuel': 'نوع الوقود',
    'carDetail.class': 'فئة السيارة',
    'carDetail.description': 'التفاصيل والوصف',
    'carDetail.reviews': 'تقييمات العملاء الموثقة',
    'carDetail.noReviews': 'لا توجد تقييمات لهذه السيارة بعد.',
    'carDetail.pricePerDay': 'السعر اليومي',
    'carDetail.bookNow': 'طلب حجز فوري',
    'carDetail.freeCancel': 'إلغاء مجاني حتى 48 ساعة قبل الرحلة',
    'carDetail.rentedVia': 'مؤجرة عبر',
    'carDetail.ownerCannotBook': 'لا يمكن لأصحاب الوكالات حجز سيارات',
    'carDetail.logInToBook': 'سجل دخولك لإتمام الحجز',
    // Client Dashboard
    'client.title': 'لوحة تحكم حجوزاتي',
    'client.sub': 'تتبع المدفوعات، وإدارة الحجوزات النشطة، وكتابة التقييمات',
    'client.noBookings': 'لا توجد حجوزات بعد',
    'client.noBookingsSub': 'لم تقم بحجز أي سيارة حتى الآن. هل أنت مستعد للانطلاق؟',
    'client.payNow': 'ادفع الآن',
    'client.cancel': 'إلغاء الحجز',
    'client.cancelRefund': 'إلغاء واسترداد المبلغ',
    'client.writeReview': 'اكتب تقييمك',
    'client.reviewed': 'تم التقييم',
    'client.refundedAlert': 'تمت معالجة الاسترداد',
    'client.refundedAmount': 'المبلغ المسترد للبطاقة',
    'client.cancelFee': 'رسوم الإلغاء',
    'client.leaveReviewTitle': 'ترك تقييم للسيارة',
    'client.leaveReviewSub': 'شارك تجربتك في استئجار هذه السيارة. رأيك يساعد السائقين الآخرين!',
    'client.ratingScore': 'نقاط التقييم',
    'client.comment': 'تعليق التقييم',
    // Owner Dashboard
    'owner.title': 'لوحة تحكم الوكالة',
    'owner.sub': 'إدارة أسطول سياراتك، وحجوزات العملاء، والسجلات المالية',
    'owner.myFleet': 'أسطول سياراتي',
    'owner.bookingsLog': 'سجل الحجوزات',
    'owner.earnings': 'سجل الأرباح',
    'owner.settings': 'إعدادات الوكالة',
    'owner.addCar': 'إضافة سيارة جديدة',
    'owner.emptyFleet': 'أسطولك فارغ حالياً',
    'owner.emptyFleetSub': 'قم بتسجيل سيارة لبدء تلقي طلبات الاستئجار من العملاء.',
    'owner.images': 'إدارة الصور',
    'owner.agencyReg': 'تسجيل بيانات الوكالة',
    'owner.agencyRegSub': 'يجب تسجيل تفاصيل وكالتك أولاً قبل إضافة السيارات إلى النظام.',
    'owner.brandName': 'اسم الوكالة التجاري',
    'owner.cityBase': 'المدينة المقر',
    'owner.officeAddress': 'عنوان مكتب العمل',
    'owner.businessPhone': 'هاتف العمل للوكالة',
    'owner.descPlaceholder': 'صف خدماتك أو ميزات أسطولك...',
    'owner.submitApproval': 'إرسال لمراجعة الإدارة',
    'owner.pendingApprovalTitle': 'طلب التسجيل قيد المراجعة',
    'owner.pendingApprovalDesc': 'طلب تسجيل وكالتك قيد المراجعة حالياً من قبل إدارة المنصة.',
    'owner.checkBack': 'يرجى التحقق مرة أخرى قريباً. ستتمكن من إدارة أسطولك فور الموافقة.',
    'owner.editProfile': 'تحديث ملف الوكالة',
    'owner.submitUpdates': 'حفظ التغييرات',
    // Admin Dashboard
    'admin.title': 'لوحة التحكم الرئيسية بالنظام',
    'admin.sub': 'مقاييس المنصة العامة، ومراقبة الضمانات المالية، ومراجعة الأمن والتقارير',
    'admin.overview': 'نظرة عامة',
    'admin.agencies': 'الوكالات',
    'admin.usersRegistry': 'دليل المستخدمين',
    'admin.escrow': 'الضمان والمدفوعات',
    'admin.reviewsMod': 'إدارة التقييمات',
    'admin.totalClients': 'إجمالي العملاء',
    'admin.totalAgencies': 'إجمالي الوكالات',
    'admin.totalRevenue': 'أرباح المنصة (عمولات)',
    'admin.pendingEscrows': 'مدفوعات في الضمان',
    'admin.approve': 'موافقة',
    'admin.reject': 'رفض',
    'admin.suspend': 'تجميد الحساب',
    'admin.activate': 'تنشيط الحساب',
    'admin.delete': 'حذف',
    'admin.releaseFunds': 'تحرير المبالغ للوكالة',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('lang') || 'en');

  useEffect(() => {
    // When language changes, update HTML element settings
    localStorage.setItem('lang', language);
    document.documentElement.lang = language;
    
    // Set text direction to RTL for Arabic, LTR for others
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  const t = (key) => {
    const langDict = dictionary[language] || dictionary.en;
    return langDict[key] || dictionary.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl: language === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
